#!/usr/bin/env bash

# get some info
USER=`whoami`
HOSTNAME=`uname -n`
MEMORY1=`free -t -m | grep "Mem" | awk '{print $3" MB";}'`
MEMORY2=`free -t -m | grep "Mem" | awk '{print $2" MB";}'`
PSA=`ps -Afl | wc -l`

#System uptime
uptime=`cat /proc/uptime | cut -f1 -d.`
upDays=$((uptime/60/60/24))
upHours=$((uptime/60/60%24))
upMins=$((uptime/60%60))
upSecs=$((uptime%60))

#System load
LOAD1=`cat /proc/loadavg | awk {'print $1'}`
LOAD5=`cat /proc/loadavg | awk {'print $2'}`
LOAD15=`cat /proc/loadavg | awk {'print $3'}`

GREEN="\033[1;32m"
RESET="\033[0m"
logo="\

    888b.   d8 .d88b. 8888    .d88b 8             w              
    8  .8  dP8 8P  Y8 8ww.    8P    8 8   8 d88b w8ww .d88b 8d8b 
    8wwK' dPw8 8b  d8   \`8    8b    8 8b d8 \`Yb.  8   8.dP' 8P   
    8  Yb    8 \`Y88P' Y88P    \`Y88P 8 \`Y8P8 Y88P  Y8P \`Y88P 8  
"
printf "${GREEN}${logo}\n${RESET}"
echo -e "\
  =================================================================
   - Hostname............: $HOSTNAME
   - Release.............: `cat /etc/redhat-release`
   - Users...............: Currently `users | wc -w` user(s) logged on
  -----------------------------------------------------------------
   - Current user........: $USER
   - CPU usage...........: $LOAD1%, $LOAD5%, $LOAD15% (in 1, 5, 15 min)
   - Memory used.........: $MEMORY1 / $MEMORY2
   - Swap in use.........: `free -m | tail -n 1 | awk '{print $3}'` MB
   - Processes...........: $PSA running
   - System uptime.......: $upDays days $upHours hours $upMins minutes $upSecs seconds
  -----------------------------------------------------------------"
# print volume info
vol-status
# print gpus info:
if [ "`lspci | grep 'NVIDIA'`" ]; then
  gpu-status
fi