#!/usr/bin/env bash

# get some info
USER=`whoami`
HOSTNAME=`uname -n`
MEMORY1=`free -t -m | grep "Mem" | awk '{print $3" MB";}'`
MEMORY2=`free -t -m | grep "Mem" | awk '{print $2" MB";}'`
PSA=`ps -Afl | wc -l`

#System uptime
uptime=`cat /proc/uptime | cut -f1 -d.`
upDays=$((uptime/60/60/24))
upHours=$((uptime/60/60%24))
upMins=$((uptime/60%60))
upSecs=$((uptime%60))

#System load
LOAD1=`cat /proc/loadavg | awk {'print $1'}`
LOAD5=`cat /proc/loadavg | awk {'print $2'}`
LOAD15=`cat /proc/loadavg | awk {'print $3'}`

GREEN="\033[1;32m"
RESET="\033[0m"
logo="\
                ,,           ,,         
    .g8\"\"\"bgd \`7MM           db         
  .dP'     \`M   MM                      
  dM'       \`   MM  ,6\"Yb. \`7MM ,pP\"Ybd 
  MM            MM 8)   MM   MM 8I   \`\" 
  MM.           MM  ,pm9MM   MM \`YMMMa. 
  \`Mb.     ,'   MM 8M   MM   MM L.   I8 
    \`\"bmmmd'  .JMML\`Moo9^Yo.JMMLM9mmmP'\
"
printf "${GREEN}${logo}\n${RESET}"
echo -e "\
  =================================================================
   - Hostname............: $HOSTNAME
   - Release.............: `cat /etc/redhat-release`
   - Users...............: Currently `users | wc -w` user(s) logged on
  -----------------------------------------------------------------
   - Current user........: $USER
   - CPU usage...........: $LOAD1%, $LOAD5%, $LOAD15% (in 1, 5, 15 min)
   - Memory used.........: $MEMORY1 / $MEMORY2
   - Swap in use.........: `free -m | tail -n 1 | awk '{print $3}'` MB
   - Processes...........: $PSA running
   - System uptime.......: $upDays days $upHours hours $upMins minutes $upSecs seconds
  -----------------------------------------------------------------"
# print volume info
vol-status
# print gpus info:
if [ "`lspci | grep 'NVIDIA'`" ]; then
  gpu-status
fi